CREATE DATABASE Restaurant
GO

USE Restaurant
GO

--- Object: Table MigrationHistory
CREATE TABLE MigrationHistory
(
	MigrationId NVARCHAR(150) NOT NULL,
	ContextKey NVARCHAR( 300) NOT NULL,
	Model VARBINARY(MAX) NOT NULL,
	ProductVersion NVARCHAR(32) NOT NULL
	CONSTRAINT PK_MigrationHistory PRIMARY KEY CLUSTERED 
	(
		MigrationId ASC,
		ContextKey ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--- Object: Table BookingTables
CREATE TABLE BookingTables
(
	CustomerID INT NOT NULL,
	TableID INT NOT NULL,
	BookingDate DATETIME NOT NULL,
	ExpiredTime DATETIME NOT NULL
	CONSTRAINT [PK_BookingTables] PRIMARY KEY CLUSTERED 
	(
		CustomerID ASC,
		TableID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY]
GO

--- Object:  Table Customers
CREATE TABLE Customers
(
	CustomerID INT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(MAX) NOT NULL,
	IsFemale BIT NOT NULL,
	Phonenumber NVARCHAR(MAX) NOT NULL,
	CMND NVARCHAR(MAX) NOT NULL,
	Status INT NOT NULL
	CONSTRAINT PK_Customers PRIMARY KEY CLUSTERED 
	(
		CustomerID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--- Object: Table Employees
CREATE TABLE Employees
(
	EmployeeID INT IDENTITY(1,1) NOT NULL,
	Username NVARCHAR(MAX) NOT NULL,
	Password NVARCHAR(MAX) NOT NULL,
	Name NVARCHAR(MAX) NOT NULL,
	LastName NVARCHAR(MAX) NOT NULL,
	Email NVARCHAR(MAX) NOT NULL,
	IsFemale BIT NOT NULL,
	DataOfBirth DATETIME NOT NULL,
	PhoneNumber NVARCHAR(MAX) NOT NULL,
	Address NVARCHAR(MAX) NOT NULL,
	CMND NVARCHAR(MAX) NOT NULL,
	IsAdmin BIT	NOT NULL,
	Status INT NOT NULL 
	CONSTRAINT PK_Employees PRIMARY KEY CLUSTERED 
	(
		EmployeeID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--- Object: Table FoodDrinks  
CREATE TABLE FoodDrinks
(
	
	FoodDrinkID INT IDENTITY(1,1) NOT NULL,
	FoodDrinkName NVARCHAR(MAX) NOT NULL DEFAULT N'No Name',
	FoodPrice FLOAT NOT NULL DEFAULT 0,
	ImageURL NVARCHAR(MAX) NULL,
	Description NVARCHAR(MAX) NULL,
	IsAvailable BIT NOT NULL,
	IsFood BIT NOT NULL,

	CONSTRAINT PK_FoodDrinks PRIMARY KEY CLUSTERED 
	(
		FoodDrinkID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--- Object:  Table OrderDetails
CREATE TABLE OrderDetails
(
	OrderID INT NOT NULL,
	FoodDrinkID INT NOT NULL,
	Quantity INT NOT NULL,
	Note NVARCHAR(MAX) NOT NULL,
	Price REAL NOT NULL
	CONSTRAINT PK_OrderDetails PRIMARY KEY CLUSTERED 
	(
		OrderID ASC,
		FoodDrinkID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--- Object: Table Orders
CREATE TABLE Orders
(
	OrderID INT IDENTITY(1,1) NOT NULL,
	OrderDate DATETIME NOT NULL,
	IsPaid BIT	NOT NULL,
	Total REAL NOT NULL,
	CustomerID INT NOT NULL,
	TableID INT NOT NULL,
	EmployeeID INT NOT NULL
	CONSTRAINT PK_Orders PRIMARY KEY CLUSTERED 
	(
		OrderID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY]
GO

--- Object:  Table Tables   
CREATE TABLE Tables
(
	TableID INT IDENTITY(1,1) NOT NULL,
	TableName NVARCHAR(MAX) NOT NULL,
	Status INT NOT NULL
	CONSTRAINT PK_Tables PRIMARY KEY CLUSTERED 
	(
		TableID ASC
	)
	WITH 
	(
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) 
	ON [PRIMARY]
) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO